#!/bin/bash

git init

echo "Enter project name: \c"
read projName

git add .

git remote rm origin
git remote add origin "https://github.com/roboWelly/$projName"

git commit -m "Commit..."
git push origin master
